apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: lan-pool
      protocol: layer2
      addresses:
      - 192.168.12.61-192.168.12.70
      interface: enp2s0