apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-test-pvc
  namespace: storage
spec:
  storageClassName: nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi