apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-storage-pv
spec:
  capacity:
    storage: 8Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  nfs:
    path: /mnt/Generic_1TB/k3s_pool
    server: 192.168.12.50
    readOnly: false
  mountOptions:
    - vers=4
    - timeo=600
    - retrans=2