apiVersion: v1
kind: Pod
metadata:
  name: test-longhorn-pod
  namespace: test-storage
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /data
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: test-longhorn-pvc